name: Deploy via Password SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (for linting only)
        run: npm install --legacy-peer-deps

      - name: Run Prettier Auto Fix
        run: npx prettier --write "src/**/*.{js,vue}"

      - name: Run ESLint Auto Fix
        run: npx eslint --fix --ext .js,.vue src
        
        # npm run build
      # Optional: commit fixes (uncomment if you want auto-commits)
      # - name: Commit fixed code style
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git diff --cached --quiet || git commit -m "chore: auto-fix lint and prettier"
      #     git push

      - name: Deploy via SSH to Production Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Starting deployment..."

            # Go to the project directory
            cd /var/www/html/production/panel

            # Pull latest code from GitHub
            git pull origin main

            # Clean install on server to ensure correct native bindings
            rm -rf node_modules package-lock.json
            npm install --production --legacy-peer-deps

            # Run build on server to avoid native binding errors with node-sass
            npm run build

            echo "Deployment complete."

          # script: |
          #   echo "Deploying project..."
            
          #   # Navigate to the deployment folder (check if it exists, clone if not)
          #   if [ ! -d "/var/www/html/production/panel/.git" ]; then
          #     git clone https://github.com/OptimalRating/panel.git /var/www/html/production/panel/
          #   fi

          #   cd /var/www/html/production/panel

          #   # Pull the latest code from GitHub
          #   git pull origin main

          #   # Install production dependencies and build
          #   npm install --production

          #   # Build the Vue.js app
          #   npm run build

          #   # Restart the application (adjust pm2 to use the right path)
          #   # pm2 restart all || pm2 start dist/ --name "optimal-panel" # Use dist if it's the build output folder for Vue.js
