name: Deploy via Password SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy with SSH and Password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Deploying project..."
            
            # Navigate to the deployment folder (check if it exists, clone if not)
            if [ ! -d "/var/www/html/production/panel/.git" ]; then
              git clone https://github.com/OptimalRating/panel.git /var/www/html/production/panel/
            fi

            cd /var/www/html/production/panel

            # Pull the latest code from GitHub
            git pull origin main

            # Install production dependencies and build
            npm install --production

            # Build the Vue.js app
            npm run build

            # Restart the application (adjust pm2 to use the right path)
            # pm2 restart all || pm2 start dist/ --name "optimal-panel" # Use dist if it's the build output folder for Vue.js

